# Generated by Django 3.0.7 on 2020-06-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffairesSansRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomPrenomLeader', models.CharField(max_length=200)),
                ('NumeroChantier', models.IntegerField()),
                ('NbreLogements', models.IntegerField()),
                ('DateFinChantier', models.DateTimeField()),
                ('MarcheChantier', models.CharField(max_length=40)),
                ('TypeChantier', models.CharField(max_length=40)),
                ('StatutChantier', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'affaires sans relation',
                'ordering': ['DateFinChantier'],
            },
        ),
    ]
